version: '3.8'
services:
  inventory-service:
    build: ./inventory-service
    ports:
      - '4001:4001'
  orders-service:
    build: ./orders-service
    ports:
      - '4000:4000'
    environment:
      - INVENTORY_URL=http://inventory-service:4001
    depends_on:
      - inventory-service
