import path from 'path';
import { Verifier } from '@pact-foundation/pact';
import { createApp } from './app';

const PORT = 4444;
const PACT_FILE = path.resolve(
  __dirname,
  '../../orders-service/pacts/orders-service-inventory-service.json',
);

// Contract verification (provider side).
// Starts inventory-service for real on a test port and checks that it
// fulfills, request by request, the contract that orders-service generated
// as the consumer (see orders-service/src/inventoryClient.pact.test.ts).
// Requires having run `npm run test:pact` in orders-service at least once,
// so the contract file exists.
describe('Pact verification: inventory-service (provider)', () => {
  it('fulfills the contract generated by orders-service', () => {
    const server = createApp().listen(PORT);

    return new Verifier({
      provider: 'inventory-service',
      providerBaseUrl: `http://localhost:${PORT}`,
      pactUrls: [PACT_FILE],
      stateHandlers: {
        'sku-1 exists in the catalog': () => Promise.resolve('ok'),
        'sku-1 has enough stock': () => Promise.resolve('ok'),
        'sku-1 does not have enough stock': () => Promise.resolve('ok'),
      },
    })
      .verifyProvider()
      .finally(() => server.close());
  });
});
